name: Commit comments
on:
  push:
    branches:
      - main

jobs:
  comments:
    name: Commit comments
    runs-on: ubuntu-latest
    steps:
      - name: Comment on commit
        uses: changespreview/comments-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
